--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: nikol
--

CREATE TABLE public.actors (
    id integer NOT NULL,
    age integer,
    name text,
    gender text
);


ALTER TABLE public.actors OWNER TO nikol;

--
-- Name: movies; Type: TABLE; Schema: public; Owner: nikol
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    name text,
    releasedate timestamp without time zone
);


ALTER TABLE public.movies OWNER TO nikol;

--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: nikol
--

COPY public.actors (id, age, name, gender) FROM stdin;
1	27	Sarah	female
2	27	Nikolai	male
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: nikol
--

COPY public.movies (id, name, releasedate) FROM stdin;
1	Lord of the Rings	2016-06-22 19:10:25
2	Harry Potter	2016-06-23 19:10:25
\.


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: nikol
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: nikol
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

