"""empty message

Revision ID: ad7a836df0d1
Revises: d557101ebb30
Create Date: 2020-06-19 18:19:01.830671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7a836df0d1'
down_revision = 'd557101ebb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('gender', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('movies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('releasedate', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('People')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'People',
        sa.Column(
            'id',
            sa.INTEGER(),
            server_default=sa.text('nextval(\'"People_id_seq"\'::regclass)'),
            autoincrement=True,
            nullable=False),
        sa.Column(
            'name',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'catchphrase',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True),
        sa.PrimaryKeyConstraint(
            'id',
            name='People_pkey'))
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
